#pragma once

#define VIEWPORT_WIDTH 1024
#define VIEWPORT_HEIGHT 720

#define PLANET_WIDTH (VIEWPORT_WIDTH * 2)

#define BUNKER_BULLET_RADIUS 3.0f

#define NUMERO_PIANETI 8
#define NUMERO_BUNKER 7
#define NUMERO_BUNKER2 3

#define SHIP_MAX_FUEL 10000.f

